a = str("Jerry SLD")
print(a.replace("SLD","DLC"))
print("!".join(a))
print(a.strip("rr"))
print(a.lstrip("JSDL"))
print(a.rstrip("JSDL"))
print(a.removeprefix("JSLD"))
print(a.removesuffix("SLD"))
print(a.partition(" "))
print(a.rpartition("r"))
print(a.split())
print(a.rsplit())
print(("Jerry\nsld".splitlines()))
print(a.count("r"))
print(a.find("L"))
#为什么输入r会显示数量啊
print(a.startswith("Je"))
print(a.endswith("SLD"))
print(a.isspace())
print(a.isspace())
print(a.isalpha())
print(a.isalnum())
print(a.isupper())
print(a.islower())
print(a.upper())
print(a.lower())
